### ISSUE TITLE
Syncing service crashes because the core crashes

### ISSUE THREAD

**Issue by JulioV** [denzilferreira/aware-client#106]
There are several times when the client crashes due to a DISK I/O exception and this causes a long sync schedule to crash as well. This happens when the client is in a study. The problem could be due to a concurrency issue with SQLite

`02-07 15:36:39.021 31204-31204/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.aware.plugin.google.activity_recognition, PID: 31204
                                                   java.lang.RuntimeException: Unable to stop service com.aware.utils.WebserviceHelper@2cc9000a: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
                                                       at android.app.ActivityThread.handleStopService(ActivityThread.java:2973)
                                                       at android.app.ActivityThread.access$2200(ActivityThread.java:155)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1420)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
                                                    Caused by: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
                                                       at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
                                                       at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
                                                       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
                                                       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
                                                       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
                                                       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
                                                       at android.content.ContentResolver.query(ContentResolver.java:497)
                                                       at android.content.ContentResolver.query(ContentResolver.java:422)
                                                       at com.aware.Aware.getSetting(Aware.java:1005)
                                                       at com.aware.utils.WebserviceHelper.onDestroy(WebserviceHelper.java:426)
                                                       at android.app.ActivityThread.handleStopService(ActivityThread.java:2954)
                                                       at android.app.ActivityThread.access$2200(ActivityThread.java:155) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1420) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702) `

This is also present in the Accelerometer:
`02-06 12:24:11.960 5743-11551/? E/AndroidRuntime: FATAL EXCEPTION: AWARE::Accelerometer
                                                  Process: com.aware.phone, PID: 5743
                                                  android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
                                                      at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
                                                      at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
                                                      at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
                                                      at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
                                                      at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
                                                      at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
                                                      at android.content.ContentResolver.query(ContentResolver.java:497)
                                                      at android.content.ContentResolver.query(ContentResolver.java:422)
                                                      at com.aware.Aware.getSetting(Aware.java:1005)
                                                      at com.aware.Accelerometer.onSensorChanged(Accelerometer.java:116)
                                                      at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:405)
                                                      at android.os.MessageQueue.nativePollOnce(Native Method)
                                                      at android.os.MessageQueue.next(MessageQueue.java:143)
                                                      at android.os.Looper.loop(Looper.java:122)
                                                      at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by denzilferreira** [comment]
Fixed.
