### ISSUE TITLE
Attempt to write readonly database

### ISSUE THREAD

**Issue by JulioV** [denzilferreira/aware-client#121]
While sensing in a study this exception pop up.

```
02-16 07:38:54.742 17480-17480/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.aware.phone, PID: 17480
                                                   android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
                                                       at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                       at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
                                                       at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                       at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                       at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
                                                       at com.aware.providers.Traffic_Provider.insert(Traffic_Provider.java:152)
                                                       at android.content.ContentProvider$Transport.insert(ContentProvider.java:236)
                                                       at android.content.ContentResolver.insert(ContentResolver.java:1205)
                                                       at com.aware.Traffic$1.run(Traffic.java:75)
                                                       at android.os.Handler.handleCallback(Handler.java:746)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)

```

**Comment by denzilferreira** [comment]
Fixed.
