### ISSUE TITLE
System error right after start syncing

### ISSUE THREAD

**Issue by JulioV** [denzilferreira/aware-client#127]
I got these logs after starting a syncing cycle:

```
02-18 13:36:19.381 5786-10635/? D/AWARE: Tried to sync for the first time for messages
02-18 13:36:20.675 5786-10636/? D/AWARE: Syncing about to create the result
02-18 13:36:20.828 5786-10637/? D/AWARE: Syncing about to create the result
02-18 13:36:21.031 5786-10637/? W/System.err:     at com.aware.utils.WebserviceHelper$SyncTable.getNumberOfRecordsToSync(WebserviceHelper.java:360)
02-18 13:36:21.031 5786-10637/? W/System.err:     at com.aware.utils.WebserviceHelper$SyncTable.call(WebserviceHelper.java:554)
02-18 13:36:21.031 5786-10637/? W/System.err:     at com.aware.utils.WebserviceHelper$SyncTable.call(WebserviceHelper.java:246)
02-18 13:36:21.894 5786-10636/? D/AWARE: Syncing about to create the result
02-18 13:36:21.918 5786-10636/? D/AWARE: Syncing 9 records from locations
02-18 13:36:21.918 5786-10636/? D/AWARE: Syncing 0 out of 9 from table locations
```

**Comment by denzilferreira** [comment]
Fixed.
