### ISSUE TITLE
Exception in fused location plugin

### ISSUE THREAD

**Issue by JulioV** [denzilferreira/aware-client#143]
I got the following exceptions while in a study with the Fused Location plugin. Not sure if the exception in the Location provider is causing the plugin to break or the other way around

```
02-27 16:28:13.408 20664-20664/? E/Database: Failed to setLocale() when constructing, closing the database
                                             net.sqlcipher.database.SQLiteException: database is locked: , while compiling: select count(*) from sqlite_master;
                                                 at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
                                                 at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
                                                 at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
                                                 at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:83)
                                                 at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:49)
                                                 at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:42)
                                                 at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1772)
                                                 at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1737)
                                                 at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2354)
                                                 at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1101)
                                                 at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1068)
                                                 at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1017)
                                                 at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1178)
                                                 at com.aware.utils.DatabaseHelper.getDatabaseFile(DatabaseHelper.java:240)
                                                 at com.aware.utils.DatabaseHelper.getWritableDatabase(DatabaseHelper.java:184)
                                                 at com.aware.providers.Locations_Provider.initialiseDatabase(Locations_Provider.java:99)
                                                 at com.aware.providers.Locations_Provider.query(Locations_Provider.java:215)
                                                 at android.content.ContentProvider.query(ContentProvider.java:966)
                                                 at android.content.ContentProvider$Transport.query(ContentProvider.java:211)
                                                 at android.content.ContentResolver.query(ContentResolver.java:478)
                                                 at android.content.ContentResolver.query(ContentResolver.java:422)
                                                 at com.aware.plugin.google.fused_location.Plugin.checkGeofences(Plugin.java:146)
                                                 at com.aware.plugin.google.fused_location.Plugin.onStartCommand(Plugin.java:136)
                                                 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2924)
                                                 at android.app.ActivityThread.access$2100(ActivityThread.java:155)
                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                 at android.os.Looper.loop(Looper.java:135)
                                                 at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
02-27 16:28:13.410 20664-20664/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.aware.plugin.google.fused_location, PID: 20664
                                                   java.lang.RuntimeException: Unable to start service com.aware.plugin.google.fused_location.Plugin@9d916d2 with Intent { cmp=com.aware.plugin.google.fused_location/.Plugin }: java.lang.NullPointerException: Attempt to invoke virtual method 'net.sqlcipher.Cursor net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(net.sqlcipher.database.SQLiteDatabase$CursorFactory, java.lang.String, java.lang.String[], java.lang.String)' on a null object reference
                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2941)
                                                       at android.app.ActivityThread.access$2100(ActivityThread.java:155)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'net.sqlcipher.Cursor net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(net.sqlcipher.database.SQLiteDatabase$CursorFactory, java.lang.String, java.lang.String[], java.lang.String)' on a null object reference
                                                       at net.sqlcipher.database.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:330)
                                                       at net.sqlcipher.database.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:280)
                                                       at com.aware.providers.Locations_Provider.query(Locations_Provider.java:229)
                                                       at android.content.ContentProvider.query(ContentProvider.java:966)
                                                       at android.content.ContentProvider$Transport.query(ContentProvider.java:211)
                                                       at android.content.ContentResolver.query(ContentResolver.java:478)
                                                       at android.content.ContentResolver.query(ContentResolver.java:422)
                                                       at com.aware.plugin.google.fused_location.Plugin.checkGeofences(Plugin.java:146)
                                                       at com.aware.plugin.google.fused_location.Plugin.onStartCommand(Plugin.java:136)
                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2924)
                                                       at android.app.ActivityThread.access$2100(ActivityThread.java:155) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702) 
```

**Comment by denzilferreira** [comment]
Fixed.
