### ISSUE TITLE
Concurrency crash

### ISSUE THREAD

**Issue by JulioV** [denzilferreira/aware-client#178]
I unlocked a phone running the latest dev in M 6.0.1 on a study with 5 plugins and got this exception:

```
03-30 19:19:56.115 24746-24746/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.aware.phone, PID: 24746
                                                   net.sqlcipher.database.SQLiteDiskIOException: disk I/O error: COMMIT;
                                                       at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
                                                       at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2171)
                                                       at net.sqlcipher.database.SQLiteDatabase.endTransaction(SQLiteDatabase.java:716)
                                                       at com.aware.providers.Traffic_Provider.insert(Traffic_Provider.java:152)
                                                       at android.content.ContentProvider$Transport.insert(ContentProvider.java:263)
                                                       at android.content.ContentResolver.insert(ContentResolver.java:1229)
                                                       at com.aware.Traffic$1.run(Traffic.java:75)
                                                       at android.os.Handler.handleCallback(Handler.java:746)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by denzilferreira** [comment]
Should be fixed in latest.
