### ISSUE TITLE
View Cards crash

### ISSUE THREAD

**Issue by JulioV** [denzilferreira/aware-client#184]
On a phone without active sensors and with 5 active plugins I get this crash every time I click the Stream button in M.

```
04-11 17:20:14.248 10263-10326/? E/AndroidRuntime: FATAL EXCEPTION: Thread-1595
                                                   Process: com.aware.phone, PID: 10263
                                                   android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                                       at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6603)
                                                       at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:919)
                                                       at android.view.View.requestLayout(View.java:18743)
                                                       at android.view.View.requestLayout(View.java:18743)
                                                       at android.view.View.requestLayout(View.java:18743)
                                                       at android.view.View.requestLayout(View.java:18743)
                                                       at android.view.View.requestLayout(View.java:18743)
                                                       at android.view.View.requestLayout(View.java:18743)
                                                       at android.view.View.requestLayout(View.java:18743)
                                                       at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:360)
                                                       at android.view.View.requestLayout(View.java:18743)
                                                       at android.widget.AbsListView.requestLayout(AbsListView.java:1975)
                                                       at android.view.View.requestLayout(View.java:18743)
                                                       at android.view.View.requestLayout(View.java:18743)
                                                       at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:360)
                                                       at android.view.View.requestLayout(View.java:18743)
                                                       at android.widget.TextView.checkForRelayout(TextView.java:7177)
                                                       at android.widget.TextView.setText(TextView.java:4352)
                                                       at android.widget.TextView.setText(TextView.java:4209)
                                                       at android.widget.TextView.setText(TextView.java:4184)
                                                       at com.aware.plugin.google.fused_location.ContextCard$3.run(ContextCard.java:124)
                                                       at java.lang.Thread.run(Thread.java:818)
```

**Comment by denzilferreira** [comment]
Should be fixed in latest.
