### ISSUE TITLE
Crash related to SSL certificates. Null pointer exception

### ISSUE THREAD

**Issue by JulioV** [denzilferreira/aware-client#213]
I found the following exceptions while collecting data with the latest dev:
```

07-15 23:11:00.240 8808-8808/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.aware.phone, PID: 8808
                                                 java.lang.RuntimeException: Unable to start service com.aware.Installations@abbbb26 with Intent { cmp=com.aware.phone/com.aware.Installations }: java.lang.NullPointerException: Attempt to get length of null array
                                                     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3045)
                                                     at android.app.ActivityThread.-wrap17(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                  Caused by: java.lang.NullPointerException: Attempt to get length of null array
                                                     at com.aware.utils.SSLManager.getCertificate(SSLManager.java:471)
                                                     at com.aware.utils.SSLManager.handleUrl(SSLManager.java:90)
                                                     at com.aware.utils.Aware_Sensor.onStartCommand(Aware_Sensor.java:127)
                                                     at com.aware.Installations.onStartCommand(Installations.java:129)
                                                     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3028)
                                                     at android.app.ActivityThread.-wrap17(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618
```
```
07-16 06:14:36.039 10072-10072/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.aware.plugin.google.activity_recognition, PID: 10072
                                                   java.lang.RuntimeException: Unable to start service com.aware.utils.Scheduler@9f38edf with Intent { flg=0x4 cmp=com.aware.plugin.google.activity_recognition/com.aware.utils.Scheduler (has extras) }: java.lang.NullPointerException: Attempt to get length of null array
                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3045)
                                                       at android.app.ActivityThread.-wrap17(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                    Caused by: java.lang.NullPointerException: Attempt to get length of null array
                                                       at com.aware.utils.SSLManager.getCertificate(SSLManager.java:471)
                                                       at com.aware.utils.SSLManager.handleUrl(SSLManager.java:90)
                                                       at com.aware.utils.Aware_Sensor.onStartCommand(Aware_Sensor.java:127)
                                                       at com.aware.utils.Scheduler.onStartCommand(Scheduler.java:991)
                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3028)
                                                       at android.app.ActivityThread.-wrap17(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```

**Comment by denzilferreira** [comment]
This was caused by a change in Ion libraries. I don't see this anymore in current development branch.
