### ISSUE TITLE
Warning / Error in AsyncStudyCheck

### ISSUE THREAD

**Issue by NBerkel** [denzilferreira/aware-client#81]
Function AsyncStudyCheck: https://github.com/denzilferreira/aware-client/blob/master/aware-core/src/main/java/com/aware/Aware.java#L294

`11-18 21:12:11.511 27835-28652/com.aware.phone W/System.err: org.json.JSONException: Value {"status":true,"config":"{\"sensors\":[{\"setting\":\"status_applications\",\"value\":\"true\"},{\"setting\":\"status_notifications\",\"value\":\"true\"},{\"setting\":\"status_crashes\",\"value\":\"true\"},{\"setting\":\"status_battery\",\"value\":\"true\"},{\"setting\":\"webservice_silent\",\"value\":\"true\"}],\"plugins\":[{\"plugin\":\"com.aware.plugin.contingency\",\"settings\":[{\"setting\":\"status_plugin_contingency\",\"value\":\"true\"}]},{\"plugin\":\"com.aware.plugin.device_usage\",\"settings\":[{\"setting\":\"status_plugin_device_usage\",\"value\":\"true\"}]}]}"} at 0 of type org.json.JSONObject cannot be converted to boolean`

```
11-18 21:12:11.512 27835-28652/com.aware.phone W/System.err:     at com.aware.Aware$AsyncStudyCheck.doInBackground(Aware.java:315)
11-18 21:12:11.512 27835-28652/com.aware.phone W/System.err:     at com.aware.Aware$AsyncStudyCheck.doInBackground(Aware.java:293)
```

**Comment by NBerkel** [comment]
Resolved: https://github.com/denzilferreira/aware-client/commit/21837436b481425dcf562ba3f029cb0ea261de6c
